[2025-03-09T21:12:49.952+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-09T21:12:50.011+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_submit_operator_example.submit_spark_job scheduled__2023-02-11T00:00:00+00:00 [queued]>
[2025-03-09T21:12:50.053+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_submit_operator_example.submit_spark_job scheduled__2023-02-11T00:00:00+00:00 [queued]>
[2025-03-09T21:12:50.054+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-03-09T21:12:50.145+0000] {taskinstance.py:2889} INFO - Executing <Task(SparkSubmitOperator): submit_spark_job> on 2023-02-11 00:00:00+00:00
[2025-03-09T21:12:50.172+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=854) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-09T21:12:50.177+0000] {standard_task_runner.py:72} INFO - Started process 866 to run task
[2025-03-09T21:12:50.172+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'spark_submit_operator_example', 'submit_spark_job', 'scheduled__2023-02-11T00:00:00+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/spark_submit.py', '--cfg-path', '/tmp/tmphg4tnlod']
[2025-03-09T21:12:50.178+0000] {standard_task_runner.py:105} INFO - Job 50: Subtask submit_spark_job
[2025-03-09T21:12:50.329+0000] {task_command.py:467} INFO - Running <TaskInstance: spark_submit_operator_example.submit_spark_job scheduled__2023-02-11T00:00:00+00:00 [running]> on host 44a6e3229ce1
[2025-03-09T21:12:50.627+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spark_submit_operator_example' AIRFLOW_CTX_TASK_ID='submit_spark_job' AIRFLOW_CTX_EXECUTION_DATE='2023-02-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-02-11T00:00:00+00:00'
[2025-03-09T21:12:50.630+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-09T21:12:50.747+0000] {base.py:84} INFO - Retrieving connection 'spark_default'
[2025-03-09T21:12:50.757+0000] {spark_submit.py:474} INFO - Spark-Submit cmd: spark-submit --master spark://spark:7077 --num-executors 2 --executor-cores 1 --executor-memory 1g --driver-memory 1g --name SparkTest --verbose --deploy-mode client /opt/***/jobs/test_pyspark_job.py
[2025-03-09T21:12:51.477+0000] {spark_submit.py:641} INFO - /home/***/.local/lib/python3.12/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2025-03-09T21:12:51.481+0000] {spark_submit.py:641} INFO - /home/***/.local/lib/python3.12/site-packages/pyspark/bin/spark-class: line 71: /usr/lib/jvm/java-11-openjdk-amd64/bin/java: No such file or directory
[2025-03-09T21:12:51.482+0000] {spark_submit.py:641} INFO - /home/***/.local/lib/python3.12/site-packages/pyspark/bin/spark-class: line 97: CMD: bad array subscript
[2025-03-09T21:12:51.545+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 177, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 567, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark:7077 --num-executors 2 --executor-cores 1 --executor-memory 1g --driver-memory 1g --name SparkTest --verbose --deploy-mode client /opt/***/jobs/test_pyspark_job.py. Error code is: 1.
[2025-03-09T21:12:51.639+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=spark_submit_operator_example, task_id=submit_spark_job, run_id=scheduled__2023-02-11T00:00:00+00:00, execution_date=20230211T000000, start_date=20250309T211250, end_date=20250309T211251
[2025-03-09T21:12:51.669+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-09T21:12:51.670+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 50 for task submit_spark_job (Cannot execute: spark-submit --master spark://spark:7077 --num-executors 2 --executor-cores 1 --executor-memory 1g --driver-memory 1g --name SparkTest --verbose --deploy-mode client /opt/***/jobs/test_pyspark_job.py. Error code is: 1.; 866)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 177, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 567, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark:7077 --num-executors 2 --executor-cores 1 --executor-memory 1g --driver-memory 1g --name SparkTest --verbose --deploy-mode client /opt/***/jobs/test_pyspark_job.py. Error code is: 1.
[2025-03-09T21:12:51.739+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-09T21:12:51.794+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-09T21:12:51.801+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
